### PR TITLE
Adding `AppendType` method to add Type to Schema object at runtime

### PR DESCRIPTION
**Pull request by robinskumar73**

### CODE REVIEW

**Comment by sAbakumoff** [comment]
This is exactly what I need for my project. Hope that it will be merged soon!

**Comment by chris-ramon** [comment]
lgtm :+1:  — thanks a lot @robinskumar73

**Comment by sAbakumoff** [comment]
Great to see that it has been merged. Is there any estimate on when it would be released?

**Comment by chris-ramon** [comment]
> Great to see that it has been merged. Is there any estimate on when it would be released?

Yes, pretty neat feature, to add types on runtime; what do you mean with *release*? 😃

**Comment by sAbakumoff** [comment]
@chris-ramon  I mean that the latest release which I can see on the Releases tab in github does not include this change..I thought that it will be the new release that will include this change..

**Comment by chris-ramon** [comment]
> @chris-ramon I mean that the latest release which I can see on the Releases tab in github does not include this change..I thought that it will be the new release that will include this change..

Ok, got it; that's a good call, thx!
Here it is: https://github.com/graphql-go/graphql/releases/tag/v7.1.0 😃

**Comment by sAbakumoff** [comment]
Awesome, thank you very much!! I used the forked version of the repo with AppendType included and waited until the official release is rolled out and now it's! You made my day

**Pull request merged**
