### PR TITLE
Concurrently resolve fields

### PR DESCRIPTION
**Pull request by sogko**
This PR addresses #106 and probably #119.
This also depends on PR #123 and has updated with changes from that PR.

**Relevant commits specifically for this PR:**
_(The other commits are not related to this PR)_

---

**https://github.com/graphql-go/graphql/commit/09574d6faa9ef710320137f0fc9b1e4d02c6e2f6 Ensure rw-safety of `ExecutionContext.errors` which will be read/written by multiple routines/threads later**

Uses `sync.RWMutex` to ensure safety of `ExecutionContext.errors`.

If the executor encounters errors while resolving fields (e.g. from recovering from panic or when `ResolveFn` returns an `error`),  it will collect it and add to a list of errors, which will then be returned in `graphql.Result`.

Since this will be done concurrently if we use go-routines to resolve fields, this has to be thread-safe.

---

**https://github.com/graphql-go/graphql/commit/ab3b083f9119b0aaf8c98ec716524dcf1c231780 Experimental implementation of concurrently resolving fields**

This change is contained in `executeFields(...)`.

For each field to be resolved, create a go-routine to resolve a field. `sync.WaitGroup` is used to wait for all fields to complete.
This will happen for each field that has sub-fields as well.

Given the following query:

``` graphql
query Bar {
  article {
    id
    author {
      id
      name
    }
  }
  feed {
    title
    body
    author {
      id
      name
    }
  }
}
```

```
  Bar ---> article ---> id
      |           |
      |            --> author ---> id
      |                      |
      |                       ---> name
      ---> feed ---> title
                |
                ---> body
                |
                ---> author ---> id
                            |
                            ---> name
```
1. `article` and `feed` will be resolved concurrently.
2. Within `article`: `id` and `author` will be resolved concurrently.
3. Within `article.author`: `id` and `name` will be resolved concurrently.
4. Within `feed`: `title`, `body` and `author` will be resolved concurrently.
5. Within `feed.author`: `id` and `name` will be resolved concurrently.

Cheers!

### CODE REVIEW

**Comment by sogko** [comment]
More discussion regarding improvements and benchmarks over sogko/graphql#20 and sogko/graphql#21 

Thanks to @andreas  & @mleonard87 

Cheers!

**Comment by Matthias247** [comment]
Hi all,
I also think parallel resolving is useful in graphql-go. However I don't think it should be implicit/automatic, like it is implemented in this PR.

I see multiple drawbacks to that:
- Resolving "simple" fields, like getting a field from a plain old struct which was returned from the parent resolver, will actually get slower and have more overhead since we now spawn a goroutine and require the associated resources for it. I guess simple fields probably make up at least have of the fields in a query.
- Resolving other fields, e.g. where the parent returns a interface and the resolver for the fields calls method on it, requires an extra level of thread safety compared to before - because the interface would be called in parallel by multiple goroutines in parallel. Before the PR I think we have been able to return a unique instance of the interface for that graphql request and it would not have had the need to be thread-safe because it would only have been called from the graphql handler thread. And if the thread-safety for the sub-fields is implemented by a mutex all advantages of parallel resolving will be gone, since the child goroutines will block on that mutex.

What I would instead propose are mechanisms for explicit parallel resolving:

The most obvious thing that comes to my mind is utilizing channels as return values for `Resolve`. The executor calls the handlers similar to right now in serial. Whenever the returned value is a channel the executor stores that channel. As soon as it executor has finished calling the `Resolve` method of all child fields it will wait/receive on the channels that it might have received as return values and then use the values from the channel as the field values.

--> This would enable the implementation to choose whether to implement sequential or parallel resolve by returning scalar values or channels (and internally starting goroutines).
--> The graphql executor can stay purely single-threaded and would have no need for synchronization, as the field value and error merging would all be done in it's own thread.

As an alternative I could imagine the automatic parallel resolving like it's implemented here - but with an optional [boolean] flag per field that must be enabled to launch the field resolve in a goroutine. Like

    Resolve: func(...) {...),
    ResolveParallel: true,

However I like explicit mechanism with channels more. It would be the same as if the graphql-js executor would accept either scalar values for `Promise<T>` values as a result from `Resolve`. And if it then would wait for the result of all promises until the main fields value would be determined.

**Comment by andreas** [comment]
If we can make opt-in concurrency very easy, I think it could be a good solution. Considering the approach of returning a channel from a resolve function, a helper function could make it very easy and get rid of the boilerplate of listening to channels, re-panicking in the executor goroutine, etc.

```go
Resolve: graphql.Parallel(func(params graphql.ResolveParams) (interface{}, error) {
  // ...
})
```

I think it's less obvious how to get easy/clean opt-in concurrency support for the elements of a list, since the resolve function is tied to the list itself, not the elements. Maybe add a field to `List` which indicates whether to evaluate the list elements concurrently or not? It doesn't feel as clean though.

It would be interesting to look into the overhead of the current approach, e.g. via the new benchmarks (#22). A pool of goroutines could potentially be used to decrease the overhead and limit the number of goroutines.

**Comment by bigdrum** [comment]
Even if the go routine overhead isn't a concern, I see another potential problem with this PR. The best feature I like for graphql is the possibility and simplicity of batching/deduping requests to the backend service (e.g. plugging it with facebook/dataloader), which brings substantial performance benefit. Doing parallel in this way makes it very hard (afaict) to implement such features.

If we allow the resolve function to return a channel as @Matthias247 suggested, or a func() (interface{}, error) that I personally prefer, the batching mechanism would be possible to implement (which allow some hook to collect all such promise-like results and dispatch batched requests).

The implementation of supporting such promise-like feature might be more complicated though, and I'm still trying to figure it out a way to do it.

**Comment by bigdrum** [comment]
> Doing parallel in this way makes it very hard (afaict) to implement such features.

I take "very hard" back. It is actually possible to achieve it in some sense with some tricks of using runtime.Gosched.

**Comment by rantav** [comment]
My vote goes to opt-in concurrency. 
Would love to see this feature a reality. 
My use case: Resolving fields from many database queries. Obviously this is something that can enjoy parallelism.

**Comment by andreas** [comment]
Following this discussion, I've made a PR for opt-in parallel resolving of fields and lists: https://github.com/sogko/graphql/pull/23

**Comment by alonrolnik** [comment]
I really would like to see this going forward, my use case is the as @rantav, resolving fields from multiple DB queries which can be executed in parallel.
Any time estimation for it? is there any temporary solution that I can use in the meantime?
Thanks!

**Comment by Kliton** [comment]
Any update?

**Comment by sandeepone** [comment]
Any Update?

**Comment by eduardogalbiati** [comment]
Any update?

**Comment by Kliton** [comment]
Up

**Comment by ahmadmuzakki** [comment]
I've been experimenting to give opt-in concurency for resolving fields. Since I really need it. Is there any concern about why we discontinue this feature like as @andreas did in sogko#23?

**Comment by dvic** [comment]
I resolved the conflicts for this branch and created PR https://github.com/sogko/graphql/pull/25, but there are still many data races due to the fact that *Schema* is not safe for concurrent use.

**Comment by divoxx** [comment]
Is there a specific reason why this hasn't been finished/merged? What is pending? This makes it nearly impossible to be used in a large application with complex graphql structure and even moderate traffic.

If there is a clear definition of the rationale/direction and what's currently pending, someone else can pick it up. I'm willing to give it a stab.

**Comment by appleboy** [comment]
@chris-ramon Could you have time to take look at this?

**Comment by chris-ramon** [comment]
> @chris-ramon Could you have time to take look at this?

- Actually this PR adds experimental support for concurrency and mentioned in the top description.
> ab3b083 Experimental implementation of concurrently resolving fields

- Also another experimental support PR: https://github.com/graphql-go/graphql/pull/154

- There is a couple of up-to-date pull-requests with different approaches:
1) Returning an async function: https://github.com/graphql-go/graphql/pull/213
```go
Resolve: func(p graphql.ResolveParams) (interface{}, error) {
  return func() (interface{}, error) {
    // runs within a goroutine
  }, nil
},
```

2) Returning a channel https://github.com/graphql-go/graphql/pull/357
```go
ch := make(graphql.ResolvePromise, 1)
// ...
Resolve: func(p graphql.ResolveParams) (interface{}, error) {
  return graphql.ResolvePromise(ch), nil
}
```

An another approach PR against a fork:
1) Opt-in concurrency: https://github.com/sogko/graphql/pull/23
```go
Parallel: true,
Resolve: func(p graphql.ResolveParams) (interface{}, error) {
  // run within a goroutine
},
```

Which one would match your use cases @appleboy

**Comment by chris-ramon** [comment]
Thanks a lot guys! :+1:  — Closing this one in favor of https://github.com/graphql-go/graphql/pull/388, you might want to take a look to a [real-use case working example](https://gist.github.com/chris-ramon/e90e245ae79d664ec2f22e4c5682ea3b) that shows the support for concurrent resolvers.

**Pull request closed without merging**
