### PR TITLE
Port changes from `graphql-js` v0.6.0

### PR DESCRIPTION
**Pull request by sogko**
> This version introduces directives to the (still experimental) schema language and introduces a @deprecated directive for marking deprecated fields. It also improves validation error messages
- https://github.com/graphql/graphql-js/releases/tag/v0.6.0

Based of PR #123 

---

**Notable changes:**
1. https://github.com/graphql-go/graphql/pull/136/commits/f1164a67d88e15a841f05b88f3f34b9ed0652836 Deepen introspection query from 3 levels to 7
2. https://github.com/graphql-go/graphql/pull/136/commits/237fab47918359a4e16994397c514323858196fd Improve validation error message when field names conflict
3. https://github.com/graphql-go/graphql/pull/136/commits/91a3aa2ea11af3094e56df2b6f93fd42ce24963e https://github.com/graphql-go/graphql/pull/136/commits/96fc0ad1a282a05d8de5226289fed06952525647 https://github.com/graphql-go/graphql/pull/136/commits/96fc0ad1a282a05d8de5226289fed06952525647 Improve validation error messages by listing suggestions
4. https://github.com/graphql-go/graphql/pull/136/commits/b71c9064356c3cfd7036884aead7f4744ae3b31d Fixes a bug where an empty "block" list could be skipped by the printer.
5. https://github.com/graphql-go/graphql/pull/136/commits/a19ac6c9058aa4c3edc1eb539352ed8c0e4981a2 Export introspection in public API 
6. https://github.com/graphql-go/graphql/pull/136/commits/9cbbd654ac105e916dd5247d318617e53483eaa6 RFC: Schema Language Directives (graphql/graphql-js#376)
7. https://github.com/graphql-go/graphql/pull/136/commits/988ab2e8a65a3a09d15a3418ac18b83cfaa754ba RFC: Directive location: schema definition (graphql/graphql-js#382)
   -This allows directives to be defined on schema definitions.
8. https://github.com/graphql-go/graphql/pull/136/commits/1225ab0ab3ab7c683322b60605ea60f348facf69 Deprecated directive (graphql/graphql-js#384)
9. https://github.com/graphql-go/graphql/pull/136/commits/6fecefe32f24ab6b8ce7d2cbeccadb0bb0ab863d Validation: improving overlapping fields quality (graphql/graphql-js#386)

### CODE REVIEW

**Comment by F21** [comment]
@sogko Any news regarding this one?

**Comment by tsunammis** [comment]
@sogko any news ?

**Comment by mishudark** [comment]
Hi, is something blocking this pull request?
there's something that the community can do to finish this PR?

**Comment by talk-to-my-car** [comment]
up, why don't you merge this PR ?

**Comment by chris-ramon** [comment]
closing in favor of: https://github.com/graphql-go/graphql/pull/192

**Pull request closed without merging**
