### PR TITLE
Port changes from `graphql-js` v0.5.0 (April 2016 spec)

### PR DESCRIPTION
**Pull request by sogko**
Started work on porting changes from graphql-js v0.5.0 which is based on the latest April 2016 spec.

Previous port was based on v0.4.18 (pending PR #117 merge)

---

__Notable changes:__

1.  https://github.com/graphql-go/graphql/pull/123/commits/58f2928b94007b502f882eee4a9a1f82dd118603 [RFC] Proposed change to directive location introspection 
2. https://github.com/graphql-go/graphql/pull/123/commits/2322d258313c9307a838ae7fe1d19e70f57937a1 [RFC] Directives in schema language
   - ❗️Breaking Changes: `graphql.NewDirective(*graphql.Directive)` => `graphql.NewDirective(graphql.DirectiveConfig)`
   - Affects those that defined custom directives.
3. https://github.com/graphql-go/graphql/pull/123/commits/03b92b0230f165ff27078db28aceea8c1cbc2432 Move getTypeOf to execute.js and rename to defaultResolveTypeFn to mirror defaultResolveFn 
   - ❗️Breaking Changes: removed `ObjectType(interface{}, ResolveInfo) *Object` from `Abstract` interface, `Union` and `Interface` structs and moved to `executor` 
   - Affects those that directly retrieved the `ObjectType` of an `Abstract` type (`Union` / `Interface`)
4. https://github.com/graphql-go/graphql/pull/123/commits/79f48da704036914912ccfbf60e1aba6d5714ad1 Add GraphQLSchema types field
   - ❗️Breaking Changes:
   - This introduces a *breaking* change to the Type System API. Now, any individual Interface type does not have the required information to answer `GetPossibleTypes` or `IsPossibleType` without knowing the other types in the Schema. These methods were moved to the Schema API, accepting the abstract type as the first parameter.
   - This also introduces a *breaking* change to the type comparator functions: `IsTypeSubTypeOf` and `DoTypesOverlap` which now require a Schema as a first argument.
5. https://github.com/graphql-go/graphql/pull/123/commits/1e33c35ba9684a3ca02bf0de8b24688636cd3295 [RFC] Add explicit context arg to graphql execution
   - ❗️Breaking Changes
   - Removed `Schema` from `ResolveParams`, already available in `ResolveParams.Info`
   - `IsTypeOfFn` and `ResolveTypeFn` params are now struct, similar to `FieldResolveFn`
   - `context` is now available for resolving types in `IsTypeOfFn` and `ResolveTypeFn`, similar to `FieldResolveFn`
6. https://github.com/graphql-go/graphql/pull/123/commits/a241e1cac73928a834a7691328c283e413b41661 RFC: Return type overlap validation
7. https://github.com/graphql-go/graphql/pull/123/commits/e23ac77f2b1e34dfeff02469edca600cb54a3b7e Add Schema Definition to IDL.

---

__Changes to public/exported vars / func__

Previous | New | Risk
---------|-----|-------
`graphql.NewDirective(*graphql.Directive)` | `graphql.NewDirective(graphql.DirectiveConfig)` | Low-Medium
`graphql.Abstract.ObjectType(interface{}, ResolveInfo) *Object` | `removed` | Low-Medium
`graphql.Union.ObjectType(interface{}, ResolveInfo) *Object` | `removed` | Low-Medium
`graphql.Interface.ObjectType(interface{}, ResolveInfo) *Object` | `removed` | Low-Medium
`graphql.IsTypeOfFn(interface{}, ResolveInfo)` | `graphql.IsTypeOfFn(IsTypeOfParams)`  | High
`graphql.ResolveTypeFn(interface{}, ResolveInfo)` | `graphql.ResolveTypeFn(ResolveTypeParams)`  | High
`graphql.ResolveParams.Schema` | `removed`, already available in `graphql.ResolveInfo` | Low-Medium

### CODE REVIEW

**Comment by mleonard87** [comment]
When is this and #117 likely to be merged in?

**Comment by bsr203** [comment]
I was checking to see whether 0.6.0 would be supported :-)

there are first class support for `context`

https://gist.github.com/steveluscher/ffc1dfefbb10ad280c8a4c520a5c201c

**Comment by sogko** [comment]
Hi @bsr203 

Man, it was barely a month ago graphql-js 0.5.0 was released, now its 0.6.0, phew~ lol

Yeah I'll definitely try to bring up this library up to parity as quickly as possible when I get free time off work. First 0.5.0, then 0.6.0 😅

Re: breaking changes from 0.5.0 -> 0.6.0, it looks promising so far:
- We already have support for `context` using `net/x/context` with PR #98. (We should consider to begin marking `RootValue` as deprecated)
- The position of `info` being changed due to addition of `context` does not apply for `graphql-go`, since we already passed all params for `ResolveFn` through `ResolveParams` struct.

Cheers!

**Comment by sogko** [comment]
Hi guys,

Calling for comments / reviews for this PR.
This will put `graphql-go` on par with `graphql-js v0.5.0` and **fully April 2016 spec compliant.** (yay)

I know this is a huge dump of commits at the moment, because we are basically playing catch up to `graphql-js` (which just released 0.6.0 lol)

I've listed notable big changes in the original PR description, along with anything that introduces **breaking changes** to the API.

/cc: @chris-ramon @bsr203

**Pull request merged**
