### PR TITLE
Emit descriptions as block strings in `printer.Print`

### PR DESCRIPTION
**Pull request by mmmveggies**
Fixes https://github.com/graphql-go/graphql/issues/484

Adds description printing to the `printer.Print` method, with tests to verify.
Seeks to keep field/directive arguments inline if none among all siblings have a description.

### CODE REVIEW

**Comment by mmmveggies** [comment]
@bhoriuchi are y'all waiting for a release...?

**Comment by bhoriuchi** [comment]
@mmmveggies I don’t have wrote access on this project to my knowledge. Just a contributor like you.

**Comment by mikleing** [comment]
Does anyone know if this fix will get added into the code soon?

**Comment by negararazm** [comment]
Anyone with the write access?

**Pull request merged**
