### PR TITLE
Add extensions support

### PR DESCRIPTION
**Pull request by Fontinalis**
I added an `Extension` interface that enables to build extensions for the `graphql` package.
Using that, we can add support for the extensions and add tracing as an extension.

Added an example `examples/star-wars-with-trace` that shows how we could add a tracing extension. 

Using the interface we could add different extensions based on different tracing providers.

I'm interested in any kind of feedback, happy to work on this more.

Update 1:
Removed the example from the repo, and created one here 
[Fontinalis/graphql-tracing-example](https://github.com/Fontinalis/graphql-tracing-example)

### CODE REVIEW

**Comment by Fontinalis** [comment]
FYI there’s an example at [graphql-tracing-example](https://github.com/Fontinalis/graphql-tracing-example) which is a simple opentracing example based on this PR

**Comment by Fontinalis** [comment]
@chris-ramon Any update on when this will be merged or reviewed?

**Comment by Fontinalis** [comment]
@chris-ramon Any luck with looking into this and make some feedback on the PR?

**Comment by chris-ramon** [comment]
@Fontinalis thanks a lot for working on this :+1: :100: 

I've being following the progress and this looks really great to me, the extensions API is small and simple to use.

Also thanks for putting altogether and creating a neat example:

image

Merging this one and let's address further improvements in a follow-up PRs.

**Comment by zonr** [comment]
My two cents:

1. "Extension" may not be a good name under the context of Schema because it may cause confusion with [Schema Extension](https://graphql.github.io/graphql-spec/June2018/#SchemaExtension) defined in GraphQL specification.
  - However, [graphql-ruby](https://graphql-ruby.org/type_definitions/field_extensions.html) uses the name [FieldExtension](https://graphql-ruby.org/api-doc/1.9.3/GraphQL/Schema/FieldExtension).
  - Both [Sangria](https://sangria-graphql.org/learn/#middleware) and [graphql-dotnet](https://graphql-dotnet.github.io/docs/getting-started/field-middleware) refers the feature as *Middleware*.

2. `graphql-js` plans to add *middleware* (graphql/graphql-js#1516) in [v15](https://github.com/graphql/graphql-js/milestone/4) to allow extended behaviors to be added to resolvers and schema.
  - But I guess they may not have that many hooks as in this PR such as `ParseDidStart` and `ValidationDidStart`, etc..

3. The design currently binds `Extensions` to `Schema`. What do you think to pass it as part of [`ExecuteParams`](https://godoc.org/github.com/graphql-go/graphql#ExecuteParams)?

In any way, many thanks again for your hard work to bring this feature!

**Pull request merged**
