### PR TITLE
Add simple mutations and list example

### PR DESCRIPTION
**Pull request by kr15h**
This is a result of my attempt to get the mutations and lists to work. This is something that I felt seriously missing from the examples directory as with these 3 functions one can now replace a REST service almost completely. I wonder what about GraphQL and authentication...

### CODE REVIEW

**Comment by chris-ramon** [comment]
Thanks a lot @kr15h :star2:

Neat example! :+1:

What do think if we could go ahead and rename the dir:
`./examples/mutations` -> `./examples/todo` - so it becomes the official todo example :smile: 

I think test's are failing because I merged: https://github.com/graphql-go/graphql/pull/80

**Comment by kr15h** [comment]
OK @chris-cp will do.

**Comment by chris-ramon** [comment]
@kr15h would you mind update it make this mergeable? so this useful example can land away. :100:

**Comment by kr15h** [comment]
Will do.

**Comment by kr15h** [comment]
So what about the failing tests? The `graphql.FieldResolveFn` causes some trouble. I am searching for a way to fix this, but...

**Comment by chris-ramon** [comment]
@kr15h I went ahead and fixed it and did minor improvements.

So closing this in favor of [#91](https://github.com/graphql-go/graphql/pull/91). 

Thanks again! :smiley:

**Pull request closed without merging**
